name: Release to PyPI

on:
  push:
    branches:
      - main  # Primary branch for releases
      - pypi-release  # Additional branch for PyPI releases

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read  # Required for accessing repo contents

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install build tools and dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Build the package
      - name: Build the package
        run: |
          python -m build .

      # Publish to PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}